// <auto-generated />
using Cinema.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinema.WebApi.Migrations.Announced
{
    [DbContext(typeof(AnnouncedContext))]
    [Migration("20200329221906_Ann1")]
    partial class Ann1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinema.WebApi.Models.AnnouncedMovie", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Released")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Runtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Writer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AnnouncedMovies");

                    b.HasData(
                        new
                        {
                            Id = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            Actors = "Thomas W. Markle, Meghan Markle, Doria Ragland, Prince Harry",
                            Country = "UK",
                            Genre = "Documentary",
                            Plot = "Thomas Markle details his journey from raising Meghan Markle on his own to his heart attack days before her wedding to Prince Harry, Duke of Sussex. Due to his sudden fame as the father of ...",
                            Poster = "https://m.media-amazon.com/images/M/MV5BMzdiMTZmNzYtMGQ0Ni00MGUxLTg4ZWYtZDc4MjBiOTdmZTllXkEyXkFqcGdeQXVyMDkwNTkwNg@@._V1_SX300.jpg",
                            Rated = "N/A",
                            Released = "25 Aug 2020",
                            Runtime = "90 min",
                            Title = "Thomas Markle: My Story",
                            Writer = "N/A",
                            Year = "2020"
                        },
                        new
                        {
                            Id = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            Actors = "Italia Ricci, Chad Michael Murray, Jack Turner, Aliyah O'Brien",
                            Country = "USA",
                            Genre = "Drama, Romance",
                            Plot = "Ally, a final contestant on a dating show, must face her high school sweetheart when she is chosen for the Hometown Date.",
                            Poster = "https://m.media-amazon.com/images/M/MV5BNGVhMTQ5YWYtMjYyOS00OGZiLTg1OGYtN2YyZDIwOGQwYmJiXkEyXkFqcGdeQXVyNjU0NTI0Nw@@._V1_SX300.jpg",
                            Rated = "TV-G",
                            Released = "30 Aug 2020",
                            Runtime = "83 min",
                            Title = "Love in Winterland",
                            Writer = "Neal H. Dobrofsky, Tippi Dobrofsky",
                            Year = "2020"
                        },
                        new
                        {
                            Id = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            Actors = "Josh Gilmer, Amber Pauline Magdesyan, Tevy Poe, Kate Durocher",
                            Country = "USA",
                            Genre = "Comedy, Drama, Romance",
                            Plot = "Five interwoven love stories explore the ups and downs of finding love.",
                            Poster = "https://m.media-amazon.com/images/M/MV5BMTMxYTg4M2EtMDFjMy00MDI1LThjZGUtNjQwOGJlY2FhNjkwXkEyXkFqcGdeQXVyNDQ2MjQ2Mjk@._V1_SX300.jpg",
                            Rated = "N/A",
                            Released = "19 Aug 2020",
                            Runtime = "88 min",
                            Title = "What Love Looks Like",
                            Writer = "Alex Magaña",
                            Year = "2020"
                        },
                        new
                        {
                            Id = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            Actors = "Meng-Po Fu, Chia-Yen Ko",
                            Country = "Taiwan",
                            Genre = "Drama, Romance",
                            Plot = "Set in 2007, the movie tells of a complicated three-way relationship between a young singer and two people who believe in him.",
                            Poster = "https://m.media-amazon.com/images/M/MV5BMTkxZTAwYTctODY3OC00NzdkLTg3ZTUtNThmMjk5ZDAzYjRiXkEyXkFqcGdeQXVyMjk2NDAwMw@@._V1_SX300.jpg",
                            Rated = "N/A",
                            Released = "23 Aug 2020",
                            Runtime = "119 min",
                            Title = "Your Love Song",
                            Writer = "N/A",
                            Year = "2020"
                        },
                        new
                        {
                            Id = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            Actors = "Manny Montana, Nora-Jane Noone, Chris Marquette, Mary Birdsong",
                            Country = "USA",
                            Genre = "Comedy, Drama, Romance, Thriller",
                            Plot = "After his wife's death, Claude struggles to appear normal while living with a Secret.",
                            Poster = "https://m.media-amazon.com/images/M/MV5BMTBmYWU0ZGYtNTRjNi00MmJkLTg0OGItNjI5M2Y2ZjY4MzhkXkEyXkFqcGdeQXVyMjM2NzM3Mjc@._V1_SX300.jpg",
                            Rated = "N/A",
                            Released = "15 Sep 2020",
                            Runtime = "103 min",
                            Title = "I Hate the Man in My Basement",
                            Writer = "Dustin Cook",
                            Year = "2020"
                        },
                        new
                        {
                            Id = "9f855797-11d1-4634-b489-1ae58211ee98",
                            Actors = "Anne Hathaway, Ben Affleck, Rosie Perez, Willem Dafoe",
                            Country = "USA",
                            Genre = "Crime, Drama, Mystery, Thriller",
                            Plot = "A veteran D.C. journalist loses the thread of her own narrative when a guilt-propelled errand for her father thrusts her from byline to unwitting subject in the very story she's trying to break. Adapted from Joan Didion's namesake novel.",
                            Poster = "https://m.media-amazon.com/images/M/MV5BMWI3ODZlNjgtNWM4OC00MDFhLTg2MmYtYjk3M2I0OWJmZmE2XkEyXkFqcGdeQXVyODkzNTgxMDg@._V1_SX300.jpg",
                            Rated = "R",
                            Released = "8 Sep 2020",
                            Runtime = "115 min",
                            Title = "The Last Thing He Wanted",
                            Writer = "Marco Villalobos (screenplay by), Dee Rees (screenplay by), Joan Didion (based on the book by)",
                            Year = "2020"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
