// <auto-generated />
using Cinema.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinema.WebApi.Migrations.Repertory
{
    [DbContext(typeof(TicketContext))]
    [Migration("20200330213457_Tickets")]
    partial class Tickets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinema.WebApi.Models.Ticket", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HallId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoveId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = "99d552f6-a5ea-4bc5-bae6-f873e43d3e54",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "22:00"
                        },
                        new
                        {
                            Id = "38979969-a611-4042-864d-56178378dfaf",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "9:00"
                        },
                        new
                        {
                            Id = "4a508e5b-f359-432d-b34a-150d49f1332a",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "0:00"
                        },
                        new
                        {
                            Id = "e7caeb2d-e632-40ae-9271-067829b465d3",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "17:00"
                        },
                        new
                        {
                            Id = "1587a985-fab5-405b-a622-f490f8a3992d",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "18:00"
                        },
                        new
                        {
                            Id = "15d466b2-06e8-49e4-82b9-ec60a1a90b96",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "5:00"
                        },
                        new
                        {
                            Id = "199be63f-15fd-4396-9984-c31cd9b14518",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "0:00"
                        },
                        new
                        {
                            Id = "51ef3239-1319-4386-9e80-6d1f03aa8244",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "12:00"
                        },
                        new
                        {
                            Id = "2707a35f-1c8f-4fab-b0aa-2f1150ad1e03",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "8:00"
                        },
                        new
                        {
                            Id = "e0778d70-122b-47c0-a12e-c04e182729b1",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "2:00"
                        },
                        new
                        {
                            Id = "be0e8e81-7d1c-4f37-8521-adc510aa42ac",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "11:00"
                        },
                        new
                        {
                            Id = "a1b602ad-c53b-4af1-b6d1-48b0d637a8ba",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "8:00"
                        },
                        new
                        {
                            Id = "0d45f245-76fa-4c5c-999d-1c1d04ebb868",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "6:00"
                        },
                        new
                        {
                            Id = "af431ef7-1ade-46bf-91e0-cde7c9bced42",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "22:00"
                        },
                        new
                        {
                            Id = "d2680fa6-74de-4fc8-9b9a-fb0eb1be2042",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "11:00"
                        },
                        new
                        {
                            Id = "a0a516c8-ad23-4cfa-b1db-1e3c41403a06",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "0:00"
                        },
                        new
                        {
                            Id = "77ac1010-6e14-4951-a111-ba83e98274d6",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "13:00"
                        },
                        new
                        {
                            Id = "2e85e693-d880-4fc0-9ddb-25e79594384f",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "16:00"
                        },
                        new
                        {
                            Id = "d91b7fcf-b10e-4bfa-bb9c-d623cd4edd7c",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "4:00"
                        },
                        new
                        {
                            Id = "91191664-df47-45f6-bbed-b5ed1e7e078f",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "3:00"
                        },
                        new
                        {
                            Id = "1c7d537f-5245-465f-b964-c801242b5b70",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "7:00"
                        },
                        new
                        {
                            Id = "fe0aca0c-40b2-4841-9b4b-13716a5c2b54",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "10:00"
                        },
                        new
                        {
                            Id = "a4c37f75-bb66-4bec-b5ae-a443220fd676",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "0:00"
                        },
                        new
                        {
                            Id = "7e25bae7-e6a8-4c6e-a4e1-eb4b398cfcff",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "6:00"
                        },
                        new
                        {
                            Id = "349a2449-e9cb-4787-9022-8f334e0ff740",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "22:00"
                        },
                        new
                        {
                            Id = "9815f7cd-9073-4624-906f-67d9ea44d70d",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "21:00"
                        },
                        new
                        {
                            Id = "01096560-bed8-42bd-b750-2f489d41d2d7",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "2:00"
                        },
                        new
                        {
                            Id = "28fdbfe2-7177-46bb-a54e-0c77cbb161ee",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "15:00"
                        },
                        new
                        {
                            Id = "506cdc04-0eb8-40cc-9591-2ee7559ced98",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "15:00"
                        },
                        new
                        {
                            Id = "38478451-700b-4c6d-8cdb-9ef6c2644da4",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "18:00"
                        },
                        new
                        {
                            Id = "6159020f-5378-4238-9c9b-f141af24ae66",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "15:00"
                        },
                        new
                        {
                            Id = "77e80d38-54b0-4862-9b16-2c1f91b24f0a",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "19:00"
                        },
                        new
                        {
                            Id = "4a01092c-64b7-4292-b951-b1fe9c2a98a7",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "8:00"
                        },
                        new
                        {
                            Id = "910ebc69-2941-4474-9926-ed63742f89e9",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "20:00"
                        },
                        new
                        {
                            Id = "db334185-efe7-488c-b557-e38a4dbc76a5",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "1:00"
                        },
                        new
                        {
                            Id = "1aae3142-0846-4c24-82bb-e2ca007aa04f",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "9f855797-11d1-4634-b489-1ae58211ee98",
                            PlayTime = "2:00"
                        },
                        new
                        {
                            Id = "f9cfa2e9-fbcc-4a59-a35f-1d6fe500a1a3",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "9f855797-11d1-4634-b489-1ae58211ee98",
                            PlayTime = "6:00"
                        },
                        new
                        {
                            Id = "19db299c-0f5a-4b95-9404-fa41c18144a4",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "9f855797-11d1-4634-b489-1ae58211ee98",
                            PlayTime = "20:00"
                        },
                        new
                        {
                            Id = "ac9f0430-b7a1-4178-9759-e5a30d653774",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "9f855797-11d1-4634-b489-1ae58211ee98",
                            PlayTime = "18:00"
                        },
                        new
                        {
                            Id = "4cb1bfc4-7aef-4830-b17b-2fad4fc88af4",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "9f855797-11d1-4634-b489-1ae58211ee98",
                            PlayTime = "8:00"
                        },
                        new
                        {
                            Id = "622d9398-dc90-48c5-8c67-b762fb075ec9",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "9f855797-11d1-4634-b489-1ae58211ee98",
                            PlayTime = "8:00"
                        },
                        new
                        {
                            Id = "6f518878-7afb-4bab-b9ba-b8c9e1de5ef3",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "9f855797-11d1-4634-b489-1ae58211ee98",
                            PlayTime = "16:00"
                        },
                        new
                        {
                            Id = "8d336485-7965-4888-aca3-b35826b125c3",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "22469aab-0419-475e-a64a-ecfc335c7321",
                            PlayTime = "11:00"
                        },
                        new
                        {
                            Id = "52e73b77-ddf0-4e48-99bc-f47d739e43d9",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "22469aab-0419-475e-a64a-ecfc335c7321",
                            PlayTime = "16:00"
                        },
                        new
                        {
                            Id = "4eced269-3e97-40f2-834a-e0e557419516",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "22469aab-0419-475e-a64a-ecfc335c7321",
                            PlayTime = "20:00"
                        },
                        new
                        {
                            Id = "3c098b4f-1f5f-472a-a6cd-eaa24812037a",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "22469aab-0419-475e-a64a-ecfc335c7321",
                            PlayTime = "7:00"
                        },
                        new
                        {
                            Id = "75df98a8-cb1b-4544-966d-f7e185f740c9",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "22469aab-0419-475e-a64a-ecfc335c7321",
                            PlayTime = "11:00"
                        },
                        new
                        {
                            Id = "74944f24-75fd-4820-b70c-e8164645e78f",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "22469aab-0419-475e-a64a-ecfc335c7321",
                            PlayTime = "16:00"
                        },
                        new
                        {
                            Id = "f72837db-3b3f-4e7e-9d4f-782b5744babd",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "22469aab-0419-475e-a64a-ecfc335c7321",
                            PlayTime = "22:00"
                        },
                        new
                        {
                            Id = "77a6bb6d-001e-4179-8d55-8d167c64eee8",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "26ba6b32-be90-443f-8ba2-890f14551457",
                            PlayTime = "6:00"
                        },
                        new
                        {
                            Id = "56cbb7cd-15be-45e7-aad6-20d19912d532",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "26ba6b32-be90-443f-8ba2-890f14551457",
                            PlayTime = "15:00"
                        },
                        new
                        {
                            Id = "01964291-6e4a-4b5e-b761-09f407b66552",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "26ba6b32-be90-443f-8ba2-890f14551457",
                            PlayTime = "14:00"
                        },
                        new
                        {
                            Id = "540ac782-b18c-41ed-bd39-cd843883acf5",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "26ba6b32-be90-443f-8ba2-890f14551457",
                            PlayTime = "15:00"
                        },
                        new
                        {
                            Id = "17f9b83a-f90a-4a03-a3c4-11a8622276dc",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "26ba6b32-be90-443f-8ba2-890f14551457",
                            PlayTime = "10:00"
                        },
                        new
                        {
                            Id = "278d9f49-3ef9-4bb4-9fa2-4b336b831c5d",
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "26ba6b32-be90-443f-8ba2-890f14551457",
                            PlayTime = "15:00"
                        },
                        new
                        {
                            Id = "a026950b-ab91-4713-a9a1-6fc8898a2f6f",
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "26ba6b32-be90-443f-8ba2-890f14551457",
                            PlayTime = "11:00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
