// <auto-generated />
using Cinema.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinema.WebApi.Migrations.Repertory
{
    [DbContext(typeof(RepertoryContext))]
    [Migration("20200401220704_repertories")]
    partial class repertories
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinema.WebApi.Models.Repertory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("HallId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoveId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Repertoires");

                    b.HasData(
                        new
                        {
                            Id = "988eec28-16b6-4a01-9b01-42c4c46c154a",
                            Day = 1,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "7:00"
                        },
                        new
                        {
                            Id = "e4c98065-bec5-4a4c-a5eb-4bf18b27d005",
                            Day = 1,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "9:30"
                        },
                        new
                        {
                            Id = "abd44f1a-763b-4b1d-8b28-1f18453ddd0e",
                            Day = 1,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "19:45"
                        },
                        new
                        {
                            Id = "17fd6d52-88c3-4f2f-9265-ef8acad4dfbf",
                            Day = 2,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "5:00"
                        },
                        new
                        {
                            Id = "88ba9f78-f749-43ba-a53d-92e401f34d3e",
                            Day = 2,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "10:30"
                        },
                        new
                        {
                            Id = "ffa5ae09-ca3c-42df-9dc8-506bc0c3821d",
                            Day = 2,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "20:45"
                        },
                        new
                        {
                            Id = "9939ac87-ad57-40d7-ae40-42dd2ccaa362",
                            Day = 3,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "4:00"
                        },
                        new
                        {
                            Id = "24d486a9-317d-4cde-85b6-d61ae53d5b6b",
                            Day = 3,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "11:30"
                        },
                        new
                        {
                            Id = "1e82b50f-0a97-442d-994e-40edc3004f61",
                            Day = 3,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "16:45"
                        },
                        new
                        {
                            Id = "027fc860-c53b-426f-92fa-39917ba87dd6",
                            Day = 4,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "3:00"
                        },
                        new
                        {
                            Id = "03319ec6-db92-4ef6-b3d2-292df0833ed6",
                            Day = 4,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "11:30"
                        },
                        new
                        {
                            Id = "845cb544-9858-40dd-bfc2-9f0db9dcb591",
                            Day = 4,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "21:45"
                        },
                        new
                        {
                            Id = "98865c20-c82a-4d79-b89c-b1a682ce0741",
                            Day = 5,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "3:00"
                        },
                        new
                        {
                            Id = "da75aa21-4503-470c-b6d5-af28b8ae7ad7",
                            Day = 5,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "13:30"
                        },
                        new
                        {
                            Id = "63791a27-319b-439e-97aa-fe737ff98a5c",
                            Day = 5,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "17:45"
                        },
                        new
                        {
                            Id = "75eb97f4-c617-4d23-9aa8-7976922a9eb2",
                            Day = 6,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "0:00"
                        },
                        new
                        {
                            Id = "46a00178-acc9-4eef-8aab-e8c7daaf39fc",
                            Day = 6,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "13:30"
                        },
                        new
                        {
                            Id = "9e742095-18b1-4ddd-b687-0b76441b367a",
                            Day = 6,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "17:45"
                        },
                        new
                        {
                            Id = "73233417-65ed-444d-a8f6-3e054c9b0a82",
                            Day = 7,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "4:00"
                        },
                        new
                        {
                            Id = "f4b260f4-b30a-458b-bf50-3a7c8347cee4",
                            Day = 7,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "13:30"
                        },
                        new
                        {
                            Id = "8a227825-424d-478f-8bee-e6ad3a25d16d",
                            Day = 7,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            PlayTime = "20:45"
                        },
                        new
                        {
                            Id = "6b8806ab-5b35-4d3f-8683-5b84e382eac6",
                            Day = 1,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "1:00"
                        },
                        new
                        {
                            Id = "bf44c5e0-c42e-48e5-8c5b-dc63e2955c84",
                            Day = 1,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "11:30"
                        },
                        new
                        {
                            Id = "bfe41058-faa1-46ab-9650-f98819d7bda3",
                            Day = 1,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "16:45"
                        },
                        new
                        {
                            Id = "790e99a9-3659-42b6-b1c5-11c415bc165b",
                            Day = 2,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "3:00"
                        },
                        new
                        {
                            Id = "325dec93-bb9a-4358-bed0-96aef589b08c",
                            Day = 2,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "9:30"
                        },
                        new
                        {
                            Id = "bb7531b9-f4f5-45c2-9d22-e7f10b896275",
                            Day = 2,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "21:45"
                        },
                        new
                        {
                            Id = "af5149a1-3827-4b39-a254-6b1bc23d543f",
                            Day = 3,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "0:00"
                        },
                        new
                        {
                            Id = "625f45ec-e197-42d4-9a80-b610f9fe6093",
                            Day = 3,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "9:30"
                        },
                        new
                        {
                            Id = "9b804dd2-acf1-4341-a601-f2e1e0a5872a",
                            Day = 3,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "18:45"
                        },
                        new
                        {
                            Id = "a685b6b3-af7d-4fd3-a84c-d53f63b8a71e",
                            Day = 4,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "4:00"
                        },
                        new
                        {
                            Id = "dfa65423-1f0a-4a82-87ec-7d6680470724",
                            Day = 4,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "13:30"
                        },
                        new
                        {
                            Id = "8915e116-5e4e-48b8-9124-fd67f74ee718",
                            Day = 4,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "20:45"
                        },
                        new
                        {
                            Id = "8b9390b5-55a5-4bf6-aed5-0c894ac1ffd8",
                            Day = 5,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "2:00"
                        },
                        new
                        {
                            Id = "2a1c452e-b979-47b1-bce7-c5b5ed7092b2",
                            Day = 5,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "9:30"
                        },
                        new
                        {
                            Id = "b5467859-e4e5-4c77-912f-2fb6ac7b057b",
                            Day = 5,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "22:45"
                        },
                        new
                        {
                            Id = "c30a2e59-af7e-4443-8e24-473cbd904530",
                            Day = 6,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "4:00"
                        },
                        new
                        {
                            Id = "22b9163f-02dd-4535-84d3-019c10343f2f",
                            Day = 6,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "14:30"
                        },
                        new
                        {
                            Id = "ce353ef5-5f5d-4216-becb-28df3bd00824",
                            Day = 6,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "18:45"
                        },
                        new
                        {
                            Id = "6eed182c-4fe7-4685-992b-3d2ddbf4ecf8",
                            Day = 7,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "1:00"
                        },
                        new
                        {
                            Id = "0fbfa8a2-55e2-4a02-bab4-6f6472f471ad",
                            Day = 7,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "13:30"
                        },
                        new
                        {
                            Id = "64f5fb78-c031-4e03-a9b1-d0a4f0bcc3b4",
                            Day = 7,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            MoveId = "59c58d93-e15b-4d2c-94a2-03e82b82d7c2",
                            PlayTime = "16:45"
                        },
                        new
                        {
                            Id = "3b55ad13-f4ff-4af2-8bfb-b52cdc81e5a2",
                            Day = 1,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "0:00"
                        },
                        new
                        {
                            Id = "124fc9a6-5709-4f21-97ae-578eece6b999",
                            Day = 1,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "11:30"
                        },
                        new
                        {
                            Id = "2d3da9bf-0997-4aa2-a8d6-6994ba2a55e7",
                            Day = 1,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "18:45"
                        },
                        new
                        {
                            Id = "3294aef1-77ff-4c64-960b-79298833b329",
                            Day = 2,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "6:00"
                        },
                        new
                        {
                            Id = "aff0f720-d1ec-48a2-b77c-753c65b2362b",
                            Day = 2,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "13:30"
                        },
                        new
                        {
                            Id = "545b32ed-7bf9-4c93-99d6-69498bc256a9",
                            Day = 2,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "20:45"
                        },
                        new
                        {
                            Id = "b57df145-fc1c-4106-b68a-33e3cf367c1e",
                            Day = 3,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "5:00"
                        },
                        new
                        {
                            Id = "9a0ea611-1277-472b-b610-f068ee6284d5",
                            Day = 3,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "11:30"
                        },
                        new
                        {
                            Id = "e808cd89-b9c8-46d0-b727-f126d8d25f57",
                            Day = 3,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "17:45"
                        },
                        new
                        {
                            Id = "a480658e-7bff-43f8-bc1e-50cabd2af102",
                            Day = 4,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "0:00"
                        },
                        new
                        {
                            Id = "1f2f00b6-dd46-4751-b23a-3a399b15f27b",
                            Day = 4,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "12:30"
                        },
                        new
                        {
                            Id = "47a905cb-4b44-4ca2-9110-408528a68609",
                            Day = 4,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "22:45"
                        },
                        new
                        {
                            Id = "03a24bcc-c587-454d-9b17-bfa0ea56f74e",
                            Day = 5,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "6:00"
                        },
                        new
                        {
                            Id = "0738dd57-6cc2-4a1d-bbe0-e123e58e8af0",
                            Day = 5,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "12:30"
                        },
                        new
                        {
                            Id = "0816d0ac-83fb-4cd6-b5b3-ec37d42bac18",
                            Day = 5,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "20:45"
                        },
                        new
                        {
                            Id = "16c74882-fb74-4811-adac-e4a3942ded2e",
                            Day = 6,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "2:00"
                        },
                        new
                        {
                            Id = "69631d70-2504-4fc0-9e53-cb633a6ba9f6",
                            Day = 6,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "10:30"
                        },
                        new
                        {
                            Id = "5cfe43cd-58d5-408e-a358-7ed522fc1ad5",
                            Day = 6,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "17:45"
                        },
                        new
                        {
                            Id = "104ce451-533f-49f8-bbcd-b67916d2f617",
                            Day = 7,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "6:00"
                        },
                        new
                        {
                            Id = "adb12d8e-c77c-48e1-8ee9-d473c73c2044",
                            Day = 7,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "11:30"
                        },
                        new
                        {
                            Id = "24cfcf55-91e2-4814-ac5f-6a701b8d176e",
                            Day = 7,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            MoveId = "164ca3af-4b7f-454f-bd07-9b8d6c3736cc",
                            PlayTime = "17:45"
                        },
                        new
                        {
                            Id = "3471724d-c1e9-4e50-8c61-417d2f65e9c8",
                            Day = 1,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "5:00"
                        },
                        new
                        {
                            Id = "02f82a4b-369b-4eb1-a25b-fcd7ba6f9d2a",
                            Day = 1,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "14:30"
                        },
                        new
                        {
                            Id = "0d051f02-644e-42ea-b18d-c15cb1778109",
                            Day = 1,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "21:45"
                        },
                        new
                        {
                            Id = "aab0e823-4a50-41bc-8e19-16f79925172f",
                            Day = 2,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "1:00"
                        },
                        new
                        {
                            Id = "5874fe1a-5fef-40af-a3c8-998d6127f18d",
                            Day = 2,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "9:30"
                        },
                        new
                        {
                            Id = "1b1be08d-c5fd-4775-af4a-dc872b294f86",
                            Day = 2,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "20:45"
                        },
                        new
                        {
                            Id = "77cea3c9-f93a-402b-8417-8a961270685f",
                            Day = 3,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "3:00"
                        },
                        new
                        {
                            Id = "d6e9e639-ba33-4ab3-99d6-3aec76f2f74c",
                            Day = 3,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "12:30"
                        },
                        new
                        {
                            Id = "0b9b0649-3c24-4bbd-875c-bcd11027a246",
                            Day = 3,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "21:45"
                        },
                        new
                        {
                            Id = "550ef24b-fdeb-443e-8b06-c9b04db44601",
                            Day = 4,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "7:00"
                        },
                        new
                        {
                            Id = "b273a4a2-7112-4b74-8fe8-b98f95d00b73",
                            Day = 4,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "11:30"
                        },
                        new
                        {
                            Id = "47d57738-c5b5-4b90-9fbe-901b9504ccef",
                            Day = 4,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "16:45"
                        },
                        new
                        {
                            Id = "5b5d036a-dea9-4293-bd50-3095f4af55d5",
                            Day = 5,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "4:00"
                        },
                        new
                        {
                            Id = "3ff3c362-0f9f-4b3f-83e5-20e499fadde4",
                            Day = 5,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "10:30"
                        },
                        new
                        {
                            Id = "e16ec183-04f8-41b6-87d0-d9f4f0db9c0b",
                            Day = 5,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "16:45"
                        },
                        new
                        {
                            Id = "2f2a94f2-0bc4-4096-acb0-b5f05661eb71",
                            Day = 6,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "6:00"
                        },
                        new
                        {
                            Id = "4000f9d2-92b4-4d50-a8e9-ebdb38df90d6",
                            Day = 6,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "12:30"
                        },
                        new
                        {
                            Id = "31b0023d-7ace-463c-b8e6-658cf970841d",
                            Day = 6,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "18:45"
                        },
                        new
                        {
                            Id = "70af2a20-7cb0-4de0-85cb-670062de0ebd",
                            Day = 7,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "1:00"
                        },
                        new
                        {
                            Id = "720442be-4c7d-45aa-b0d4-277cf7e2c8d1",
                            Day = 7,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "11:30"
                        },
                        new
                        {
                            Id = "38c8f6d0-bedc-4793-b712-17bf19526aeb",
                            Day = 7,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            MoveId = "13e6d16d-e8a9-4112-a3d0-fda72a846b17",
                            PlayTime = "20:45"
                        },
                        new
                        {
                            Id = "556af0c7-60de-49b7-98c4-6407c416129f",
                            Day = 1,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "0:00"
                        },
                        new
                        {
                            Id = "b40a88c6-69db-4d7d-8398-016a57dcae56",
                            Day = 1,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "11:30"
                        },
                        new
                        {
                            Id = "bfba14da-5319-41ef-b539-9947ba0249a2",
                            Day = 1,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "17:45"
                        },
                        new
                        {
                            Id = "f5ce36a6-ad54-4259-8e14-259c5d076967",
                            Day = 2,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "5:00"
                        },
                        new
                        {
                            Id = "7013ba14-7be2-4a12-b5d3-3cb2500ba105",
                            Day = 2,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "12:30"
                        },
                        new
                        {
                            Id = "42bede1e-4702-4710-87b1-9344abb8734c",
                            Day = 2,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "19:45"
                        },
                        new
                        {
                            Id = "a8e0bff2-b4b5-4693-a8c5-8f15aa14ef2c",
                            Day = 3,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "1:00"
                        },
                        new
                        {
                            Id = "d28ce986-8f8a-4943-bb87-47c9976fa808",
                            Day = 3,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "10:30"
                        },
                        new
                        {
                            Id = "71764a7a-dc05-49c9-a310-50f50a64bada",
                            Day = 3,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "21:45"
                        },
                        new
                        {
                            Id = "390fec00-efec-4f87-af6d-51884a87bcab",
                            Day = 4,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "1:00"
                        },
                        new
                        {
                            Id = "e33b58b1-007a-47c6-8ae8-34b4d05ef76c",
                            Day = 4,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "11:30"
                        },
                        new
                        {
                            Id = "44279d07-c413-4fb7-95e4-918893e982eb",
                            Day = 4,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "17:45"
                        },
                        new
                        {
                            Id = "7db6c863-d6f6-417a-a521-951a9eded5e9",
                            Day = 5,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "7:00"
                        },
                        new
                        {
                            Id = "c0e0c1ac-4e18-453a-9984-d3535b20e60c",
                            Day = 5,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "10:30"
                        },
                        new
                        {
                            Id = "c68a2df3-778e-49cf-b9bb-62bc4335ad5d",
                            Day = 5,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "19:45"
                        },
                        new
                        {
                            Id = "ebc2bdae-b8d4-4c13-a226-ab16eb521d4c",
                            Day = 6,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "4:00"
                        },
                        new
                        {
                            Id = "ee842dca-435e-4842-8d42-0d5512cc97a4",
                            Day = 6,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "12:30"
                        },
                        new
                        {
                            Id = "31bdd4c6-c598-4f6a-b936-688d19ca2c94",
                            Day = 6,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "20:45"
                        },
                        new
                        {
                            Id = "43ef0486-d802-4148-b87b-85d6379f3607",
                            Day = 7,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "0:00"
                        },
                        new
                        {
                            Id = "b3bca5fa-eae9-4352-b47c-39a5911712d9",
                            Day = 7,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "10:30"
                        },
                        new
                        {
                            Id = "af75f44d-ab13-487a-84b7-a96961c8be0a",
                            Day = 7,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            MoveId = "1df1dac8-0b73-486e-b1a0-ded9d9d0849c",
                            PlayTime = "22:45"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
