// <auto-generated />
using System;
using Cinema.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinema.WebApi.Migrations.Repertory
{
    [DbContext(typeof(TicketContext))]
    [Migration("20200329221303_Rep")]
    partial class Rep
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinema.WebApi.Models.Repertory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<string>("MoveId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoldTickets")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Repertoires");

                    b.HasData(
                        new
                        {
                            Id = "d140b25f-1c14-4aec-a271-be66febfcc00",
                            AvailableTickets = 30,
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            SoldTickets = 0,
                            Time = new DateTime(2020, 3, 2, 7, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "2b36a06b-be50-4669-ab12-720f5bb5d4bf",
                            AvailableTickets = 30,
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            SoldTickets = 0,
                            Time = new DateTime(2020, 3, 3, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "681ab4c0-a17f-45a4-a37a-e77d4b270ec4",
                            AvailableTickets = 30,
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            SoldTickets = 0,
                            Time = new DateTime(2020, 3, 4, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "2497ac91-eb3d-4d8f-9d2f-ad39925a698e",
                            AvailableTickets = 30,
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            SoldTickets = 0,
                            Time = new DateTime(2020, 3, 5, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "0a3b67f2-c1f4-4325-beb1-bb058fafaf7a",
                            AvailableTickets = 30,
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            SoldTickets = 0,
                            Time = new DateTime(2020, 3, 6, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "dbfff58d-0725-4449-b1bb-fbe2f23f35b7",
                            AvailableTickets = 30,
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            SoldTickets = 0,
                            Time = new DateTime(2020, 3, 7, 21, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = "3cbf7579-ab7d-4e2d-91fd-e1b7dae4e034",
                            AvailableTickets = 30,
                            MoveId = "31446c42-fa95-4f38-8b8a-c5830649ca32",
                            SoldTickets = 0,
                            Time = new DateTime(2020, 3, 8, 23, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
