// <auto-generated />
using Cinema.WebApi.Contexts;
using Cinema.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinema.WebApi.Migrations.Ticket
{
    [DbContext(typeof(ReservationContext))]
    [Migration("20200402201628_updateTickets")]
    partial class updateTickets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinema.WebApi.Models.Ticket", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RepertoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatColumn")
                        .HasColumnType("int");

                    b.Property<int>("SeatRow")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = "56a2b8c4-15a1-411f-8e12-9f283867d82d",
                            RepertoryId = "9eb6b139-02cc-4be2-b1cf-5d8145f5cfa3",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "86077ef4-ebdc-4317-821b-2668d1b0806d",
                            RepertoryId = "d464a27a-e837-4ea1-8881-77323dae42eb",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "aefc3dbf-7c10-4fb3-8880-2f6a08388355",
                            RepertoryId = "c785db64-dedb-42cd-8f7a-57ade4bc38db",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "dc94d14d-2d4f-481b-aa72-60dded52e5a3",
                            RepertoryId = "12c891d0-3a9c-40b0-93a1-e56ce23c15dd",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "e34ef4da-7fe7-49a2-a4e4-29efcb9aafe5",
                            RepertoryId = "e9c1a622-520c-4d6e-9447-12fd2523d40c",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "9cd09539-877f-4ec0-9f96-6296780e3663",
                            RepertoryId = "fd8e5615-28bc-4996-8651-0ff52f15362d",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "44a70d50-6920-4977-b009-6a7c8fbf9d70",
                            RepertoryId = "3dd1e68e-667c-42b3-bea0-29ffcc30a0e8",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "f2a7335e-b714-4d64-9dba-f1ef9c7b2a73",
                            RepertoryId = "bcf9d20a-decc-4bb1-ac1e-81a053135c94",
                            SeatColumn = 0,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "6530dfe6-cd25-40ab-b389-960f81362dfd",
                            RepertoryId = "2a8d4b29-f39b-4812-a219-3f7661842098",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "699978a5-50c1-445b-9cdb-fd762afe7c3b",
                            RepertoryId = "f288ec62-9915-412a-8e2f-a7555e60bc49",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "27ddf228-cfe6-48cb-a10c-5535d2b7f246",
                            RepertoryId = "d98821de-b8fd-4945-8c06-c912d2cb940a",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "74c6c7f9-7962-4aee-872c-a3ae406a2265",
                            RepertoryId = "533a5c82-b0ce-4e4e-afb9-cb23a7940a05",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "8623a286-fca3-4b08-ae49-5797c77e85fc",
                            RepertoryId = "66fd7189-cf10-44cc-a4e5-0f16aa07bfb9",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "e84d8db1-073c-4cfd-a0a4-63b599248d70",
                            RepertoryId = "b6b2c675-d629-4f0f-ae26-d0a9a23983e1",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "c87ea031-dd76-400d-a671-66138d9556db",
                            RepertoryId = "4f537a29-4171-4a9e-a3db-9acc950863e2",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "5bd12a91-1bd4-4d80-9a52-e32e7077154d",
                            RepertoryId = "d2f88961-adf9-4089-9198-17e5b4b99c3b",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "79c74d6b-9b15-4d16-875c-aae95d9cb32c",
                            RepertoryId = "870a16fa-a719-4491-b09a-b06ad652a1d7",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "12b145cb-b7ae-4f34-a4a0-f1e51f9f3e98",
                            RepertoryId = "5f37e508-8156-4d8e-9859-d52933a64b12",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "88f1125b-eee6-40d2-8d5c-ac4ebe13944f",
                            RepertoryId = "94fa00b6-628c-4a42-a4ca-5e3398dbdbc0",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "4cff4916-8308-44d4-a331-e1f4e44cc233",
                            RepertoryId = "40e5a01f-34d0-446f-a954-6057150ec540",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "9c28d9ba-3ef3-4adc-8010-aa58f0e3e049",
                            RepertoryId = "334fb052-927e-43ae-b032-e18de7dd81ce",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "81ec66b8-598a-41c1-84d1-43293d775cd9",
                            RepertoryId = "f1a264a5-045c-4107-9ef6-8ca65d7df47c",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "3d7a6b13-a7fb-4eb7-bfea-189c18204eda",
                            RepertoryId = "a658c6b0-20fd-43b7-a603-52bee735a01a",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "3aed820d-fad6-493a-8d6f-fab36dee333f",
                            RepertoryId = "37b06319-09db-4b97-8f78-98f51f1d8e32",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "bd5a1977-b834-4de1-8434-1a58eab420cc",
                            RepertoryId = "db2ea23f-e7ce-423e-9bc2-257b2c061d04",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "0befc9ba-f01a-4deb-a2eb-4035a9b57ab9",
                            RepertoryId = "b9df548d-dde8-4c9d-9124-420e43072641",
                            SeatColumn = 0,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "c7601144-730d-45cf-951f-7dc7ca4cd73b",
                            RepertoryId = "5bc15682-2eaa-4baf-86ea-e03db1efe9f1",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "3e2a9da7-d2d6-41ec-82b1-460ec0842072",
                            RepertoryId = "2727ab7e-65a3-437a-a403-c121c87a32bf",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "fa9e1e0d-7a7e-4aea-ac83-0537f6340060",
                            RepertoryId = "e67e8d98-37a8-4310-b51c-d2b2f4c5210f",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "e00309ed-91cd-4d60-bb36-7143386fdf82",
                            RepertoryId = "f0a03776-87cf-47b5-9a6c-679d0906d87e",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "d181b9b2-3f7b-42b9-b43f-2955dbfb6dc4",
                            RepertoryId = "b7b94c44-7346-4448-9030-5883e77047c6",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "0314675c-b5c8-4128-88d1-cb3b660a25b7",
                            RepertoryId = "8e25c8bb-a4a4-4df7-ab04-e8e2f6452a26",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "373fda93-669c-4829-bb7b-88d90f00a838",
                            RepertoryId = "ad3fe353-dca7-4fcd-bc8c-9badbaf1e811",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "5f79151e-3a11-4b7a-8a58-3de7e07b3ec7",
                            RepertoryId = "2a1fccf7-7603-4ba5-b4be-044ed500ea75",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "76b9b808-ba28-4e9f-8449-12b0843c413e",
                            RepertoryId = "a82ed5c0-e84a-481a-9c6d-78263c07e6ca",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "273d6563-d0dc-49a6-8a5f-8b5ff76caebf",
                            RepertoryId = "34e641ec-9bea-4383-8e8b-f949aa764e21",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "d756ec34-6c8f-4ec1-9974-339ed957bb3b",
                            RepertoryId = "750b85d6-9ea1-4b66-942c-4e09f432530b",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "abba757d-f122-4fad-af2e-45dac134457c",
                            RepertoryId = "00b4ebea-8f60-43c9-b1ff-091053e4f744",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "ff472d6d-8017-4e0d-a561-c78afe8f11ce",
                            RepertoryId = "14705128-16f3-4e28-8f2b-63465d15a49c",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "303a82d2-0e63-435b-bf14-305d913d59d0",
                            RepertoryId = "e0d1c58d-1db0-4705-b3cb-94e6c861737c",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "823519c5-0c26-4694-823c-fbf374f268f1",
                            RepertoryId = "b728d7fe-fa8f-4b97-be85-72a3c2990648",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "bd9174b6-d921-470c-b3f7-683b27738bf0",
                            RepertoryId = "8040c6f9-f275-4752-9363-6d12069cd828",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "ccb80471-8819-445d-8440-f364037c5a3c",
                            RepertoryId = "ef8b3693-e048-4782-9c25-22456b5230b7",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "b7df9731-2e0c-4207-a47b-23f8be3181da",
                            RepertoryId = "b8429be8-5561-434d-91a8-731a94dbd95f",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "e3421f08-d991-46e6-87bc-35f9d571f033",
                            RepertoryId = "0b1177fe-0733-42e8-a8c5-35ad8039a14e",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "5f2060d9-ad7f-44f9-8284-4e31af4425a4",
                            RepertoryId = "f563fb50-26da-4a57-9bcd-b3836614835a",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "02775d3f-5298-4ef2-b072-f241636cf951",
                            RepertoryId = "8411a5b7-699f-45d4-ab67-ee3a17338424",
                            SeatColumn = 0,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "3b71e5ae-81e6-46be-9de7-d59c70b18ea3",
                            RepertoryId = "18f8b880-1231-4028-9eb6-998e94b62b9b",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "9a7b4409-b099-4643-82e3-d04260369f43",
                            RepertoryId = "73e61eb8-e1ef-400f-a6b8-b2e07725dfb2",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "983d1635-d90d-482f-9343-eda8f393f67e",
                            RepertoryId = "524ce530-f997-44da-b118-2c88be728248",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "3f3dff7b-bd03-4740-bfd8-e8ce73a874de",
                            RepertoryId = "1367d782-f24e-4985-978d-825515f40bee",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "c34f87a2-e446-41a7-bb56-a87e4d1b5c18",
                            RepertoryId = "5417a7e6-e108-48ff-b831-6578c3680a71",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "817295d3-01a0-4cb1-bc93-41c0835db6ae",
                            RepertoryId = "c80f93cc-c780-436d-800a-f3ba02aabcdc",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "641e7b0c-a499-49fb-9eba-5f540fd66e32",
                            RepertoryId = "ef0f138d-b306-4983-a873-1222342b4368",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "7a60ef8a-b18f-4999-9de6-0ba72d4b7fb4",
                            RepertoryId = "87950de7-b4a3-430b-add8-57cb2f696aa6",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "f63c2f03-a228-4984-8587-c152fe0f0c17",
                            RepertoryId = "86d5fad3-0481-4497-9dab-b97a7da4c13c",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "a6ae7135-0468-410d-8072-9d7d96010b74",
                            RepertoryId = "2ce9ef7b-77f0-49e8-8277-fe90927f3ce7",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "73986591-922c-4bb5-8c30-55e837eb294a",
                            RepertoryId = "8ad3aba2-5caa-40ca-afdb-d62f9253ed01",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "6c5fdaac-be3a-4325-8deb-5a757439b16b",
                            RepertoryId = "4f8eb2ca-3a70-4920-8de0-5033ed304451",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "dc140af5-592b-476b-95a6-4632ac64c94b",
                            RepertoryId = "1dd5a479-a903-426e-9880-4eeef60b69f8",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "094a7fde-0cb5-47e7-b4fa-4187780d76c0",
                            RepertoryId = "f6f1670a-4eba-4d98-85f6-d4c1d37a7dec",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "86a7cd7e-70ce-4b47-afc4-2cb2563c2616",
                            RepertoryId = "f6a55375-3743-4528-8ac4-8ba93e9ba017",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "48ac1fee-62e9-435c-afdd-dee6e11a306e",
                            RepertoryId = "17738e0f-d311-4003-b6c2-7a8bfe733e20",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "856c926f-27fb-45d8-b27f-731da336a15a",
                            RepertoryId = "067273f1-2931-4cf5-9f0f-0893fa7ec83e",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "2bf35f14-f721-40c8-8c2d-7eb79d08d9c7",
                            RepertoryId = "2339db48-b2bc-481d-9d78-ebb9e32f433d",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "ded446c0-587e-4357-9355-fd74d53a34e4",
                            RepertoryId = "661ac04f-8289-4eec-9530-c648264eb9a4",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "0e13beac-6502-43e5-a0f5-f9316c21e9d1",
                            RepertoryId = "f7c4ec9d-e923-4d28-8918-ac842efc24e5",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "84f9b546-755e-4f2d-b05b-5b06a2aaf0be",
                            RepertoryId = "fa858d18-c031-4a4d-8700-7b46f21109f4",
                            SeatColumn = 0,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "4eddf3e7-c240-4d90-85b2-0606c0052327",
                            RepertoryId = "1bbd4048-bbf7-4269-a4a1-bf0510fd18db",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "dd5a5609-7de8-4cc4-ba53-70e59962f578",
                            RepertoryId = "149d67fb-796f-489b-bbe2-993073b66bc6",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "47cd1d94-55f7-47fc-9619-96473ec3a561",
                            RepertoryId = "23fc35c2-cd81-45be-bf32-b2cb1da3bc34",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "61a4ef23-beb5-4c86-89a6-0b88e2e15b9d",
                            RepertoryId = "2128363b-df77-4459-85aa-2beaf899ec4c",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "fbf02a39-fe14-49bc-83ce-2e9ed2e04b14",
                            RepertoryId = "a9c0be59-ab64-4b33-8f03-26bd93aab48e",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "23437968-5a06-4720-a283-d66aae9d3d9b",
                            RepertoryId = "a7dd1624-9980-48f4-b73a-56660e673c89",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "9166a420-157f-4d04-ac8c-97f1eda30d9e",
                            RepertoryId = "c6163527-6edf-43e2-a07b-f4889a37f70e",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "8b17efa5-3c98-45fa-98f8-3b9beee612dd",
                            RepertoryId = "f56de32e-a8d4-495b-99dc-a3867d7408f0",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "15479938-0d3b-4f09-bc86-85123c5ab33d",
                            RepertoryId = "7ed80a87-eb47-4249-8ac1-917a0800496c",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "34c37a5a-bba6-40d1-a9d5-8e8069fe676e",
                            RepertoryId = "eacf5f01-e97f-412e-9ae0-a627b999bdeb",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "d2f9c3ab-8d41-4679-a78a-1a0a636833a8",
                            RepertoryId = "9fff2c90-0b6f-4974-864c-8f54a86edb4b",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "de730b3f-ce3e-4ccf-8f87-426e050673eb",
                            RepertoryId = "a840daac-d9a9-4c16-a48a-043e43247034",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "fa58abb4-af8c-4358-bfc1-e23b4abd630d",
                            RepertoryId = "e4ed83ca-81a4-4ea0-a7ef-5e4062faa9fa",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "8571d95f-31cc-4155-902d-023ccf7adb1c",
                            RepertoryId = "29fe55f5-1a1f-40ad-8db4-9b6731040db2",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "e8780afa-cfc8-4787-b283-f97a0a989d7a",
                            RepertoryId = "c6a09e5f-f947-4c64-9b18-16aac2afe1b7",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "07af62cf-5cbb-44e5-a21b-fc8437066163",
                            RepertoryId = "7fe64e0c-3586-4164-a6b5-e336b032bd4a",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "9c5d7f24-020f-425c-9b31-487c80115812",
                            RepertoryId = "ad23b7ab-3357-4f0d-a134-25d7ed235ef6",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "16666ee7-9b67-4a6a-b949-2f13fbc7500d",
                            RepertoryId = "a1a5cd9b-768c-44c3-9da7-c159e933da5b",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "bebf9f91-90bd-497f-a753-225b8d08c08c",
                            RepertoryId = "7b0d2ec2-e0ad-4efc-ba04-8d9453fd6353",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "865194ee-39d3-4f9e-92da-1bf7651b7c2a",
                            RepertoryId = "f974f0ce-ad88-4ca0-8e1e-a0f235ebe2fd",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "138304eb-5b4b-4455-8e70-8bb5c01e3c51",
                            RepertoryId = "4b0c1825-74c9-4b7c-be7e-42a25038e481",
                            SeatColumn = 0,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "caa33b80-735e-456b-bc57-eca2b50985cc",
                            RepertoryId = "a36ce8fb-2240-4440-8fb9-2e09c1a21dba",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "2545e233-a212-4910-ad84-d5f344d4dbe8",
                            RepertoryId = "d859c610-740e-4955-878b-06fe614a1998",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "da0b974a-d121-498d-bb7a-474b68a68dc7",
                            RepertoryId = "4282c7e6-4904-4a11-83a4-bf5278775272",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "9941ec29-0cfe-4312-bb6e-e227cc5565bb",
                            RepertoryId = "646458e6-6060-4dcc-9118-b14ce4c1fe28",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "8f9fc5eb-60ff-4a53-ba21-1cbad13f6b98",
                            RepertoryId = "a1c414ac-30c6-44fa-84fe-8ed9bba25611",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "08b7ef58-d5fa-4206-ae26-b32eea75c945",
                            RepertoryId = "8cf9c962-93ad-429c-9347-6fb6022a1f37",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "b7040158-6960-4b2b-ad47-7fe8cebf4ee4",
                            RepertoryId = "0002ce82-5bf2-4b33-9d69-6c4c3f09f36a",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "8d925e14-3ac9-4a06-9ee5-14fb0a9de71b",
                            RepertoryId = "43161eb5-a4a4-455f-b402-fb7d7c73b98a",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "b813d15f-f60d-4af5-a2ac-75b780b90556",
                            RepertoryId = "921112c1-f48f-4d06-9ae8-81b8c663fa2a",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "39416e24-a44a-4a63-a476-282b2f8a73a2",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 0,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "18583d48-c919-4e72-a769-7b9a8025fdbb",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "a4d85836-80ea-4f69-bae9-2e214b5a5639",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 2,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "fc23f192-8f76-4ee5-9260-64d87e335c15",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "15e683dd-e1d0-406d-8415-c79134a16d34",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 4,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "fd62d371-28a8-421a-8d81-924cd23e7ad0",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "50a20205-dfa3-40a2-a90f-db0360ed93a8",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 1,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "2c360439-c305-41b4-beb1-3e6300098700",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "b98e3b19-d9c0-4409-a611-67a9661c5702",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 3,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "e8bb2c7a-cdbb-4083-b1c6-7fe50a5c40e4",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 4,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "4146c669-686a-4679-b91c-9f0e932c4398",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 0,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "511e8ada-26dd-4680-bd3b-1534ea696e7f",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "c180e19e-c324-4524-acf3-c7db72ef67d9",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 2,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "8e868ac6-826c-4bd4-9030-b164c835e0c1",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "3dcea516-e924-4596-a441-dfe6614ad54a",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 4,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "fd3b3a6a-6d4c-4c08-8ce8-8031031b52c9",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 0,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "e93740be-2a99-4263-b4b3-3a0578229198",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 1,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "d04c9010-0ec8-412e-8588-ba877d6780e6",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "7b57e730-0177-4df1-875a-c040ef048dda",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 3,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "bee63e41-91b0-40f6-8e4d-92a18d5292b2",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 4,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "f108fe7e-4b72-4642-b6c1-ae76fda02c2a",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 0,
                            SeatRow = 4,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "39dc52b9-7d81-46a4-bd9d-67cfc2a9c966",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 1,
                            SeatRow = 4,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "759769c2-6f26-42f2-b70c-b061d4661dab",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 2,
                            SeatRow = 4,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "a8bdd189-3541-4c7d-8230-619aaba81e07",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 3,
                            SeatRow = 4,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "5b8404e3-4d65-4ae8-8432-902dd0075571",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 4,
                            SeatRow = 4,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
