// <auto-generated />
using Cinema.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinema.WebApi.Migrations.Ticket
{
    [DbContext(typeof(TicketContext))]
    [Migration("20200402064237_newticketRepIds")]
    partial class newticketRepIds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinema.WebApi.Models.Ticket", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RepertoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatColumn")
                        .HasColumnType("int");

                    b.Property<int>("SeatRow")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = "16febd09-bc05-4d5d-a8ec-cc57a68cb71f",
                            RepertoryId = "18c4b1be-0ef2-403e-a670-fe010a670db1",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "71a32ea4-9c46-4adf-8b1e-719cb1758fc1",
                            RepertoryId = "9eb6b139-02cc-4be2-b1cf-5d8145f5cfa3",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "02eb11f4-9a59-40ef-9592-965981f83bc3",
                            RepertoryId = "d464a27a-e837-4ea1-8881-77323dae42eb",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "8cac4c68-e781-433d-acc1-2153360c04dc",
                            RepertoryId = "4dfd11e5-391a-47be-902c-99620a9eabce",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "c4e68a2f-4765-4b79-9c5c-929dda63a51f",
                            RepertoryId = "c785db64-dedb-42cd-8f7a-57ade4bc38db",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "536436d2-8abc-4ee5-8ced-7137b26851ab",
                            RepertoryId = "12c891d0-3a9c-40b0-93a1-e56ce23c15dd",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "025d6e85-d828-4670-9cb6-45409bb29357",
                            RepertoryId = "1c6173eb-e01b-4a87-8f1c-18f0fb6f4a54",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "a300f96b-b89b-40cb-9cf9-9ff8b00fd740",
                            RepertoryId = "e9c1a622-520c-4d6e-9447-12fd2523d40c",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "7d18fb63-b170-4556-a177-9f0687dd1bb7",
                            RepertoryId = "fd8e5615-28bc-4996-8651-0ff52f15362d",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "60168d6f-3b2b-4dad-bad9-0ed622a8fcd0",
                            RepertoryId = "9e798f75-e7db-4a9a-a21b-d49cbba34b01",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "35e9b37a-8883-43f3-bba1-4ad42c0e7704",
                            RepertoryId = "3dd1e68e-667c-42b3-bea0-29ffcc30a0e8",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "f7cc4df7-649f-4389-b293-78d3531c37b8",
                            RepertoryId = "bcf9d20a-decc-4bb1-ac1e-81a053135c94",
                            SeatColumn = 0,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "97ca99b8-4501-4ecb-950a-3a9ad12239b5",
                            RepertoryId = "b25e331b-eb1f-4e56-8edb-a848c019eba0",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "5d87f4c5-b875-4987-bfe2-3d696ebf80c3",
                            RepertoryId = "2a8d4b29-f39b-4812-a219-3f7661842098",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "7656eeaa-114e-4f2d-9a59-cb48bd9a9b56",
                            RepertoryId = "f288ec62-9915-412a-8e2f-a7555e60bc49",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "5af03c73-bef1-4a4c-be7a-6962f9cbed89",
                            RepertoryId = "907b2948-5efc-48b5-9cfb-3358e376d30e",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "34e04dff-4997-4f74-bc44-14b3cfb13cad",
                            RepertoryId = "d98821de-b8fd-4945-8c06-c912d2cb940a",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "a19e155e-750c-423a-8116-e757f9d2661c",
                            RepertoryId = "533a5c82-b0ce-4e4e-afb9-cb23a7940a05",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "a1f03fcd-21b2-4ac7-aa35-64f417c48cfb",
                            RepertoryId = "8076031b-7b62-4185-9b15-4ac4466b3437",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "e5c8ca6f-281c-4d04-9b20-63a486318084",
                            RepertoryId = "66fd7189-cf10-44cc-a4e5-0f16aa07bfb9",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "b221a72b-3460-4c46-80be-f43b3447f9b8",
                            RepertoryId = "b6b2c675-d629-4f0f-ae26-d0a9a23983e1",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "cfbf860f-95de-44e3-bdef-569c954d8a35",
                            RepertoryId = "4f537a29-4171-4a9e-a3db-9acc950863e2",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "f83671cd-ea31-4137-81fc-c3315dc45b3d",
                            RepertoryId = "d2f88961-adf9-4089-9198-17e5b4b99c3b",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "bb09f51e-156c-439d-b93b-c03213ffb559",
                            RepertoryId = "870a16fa-a719-4491-b09a-b06ad652a1d7",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "f53e9bc2-ed7f-49af-85e9-274ce9c00d26",
                            RepertoryId = "5f37e508-8156-4d8e-9859-d52933a64b12",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "7785bf5c-a3f7-4dfe-b4be-be2ab5590d25",
                            RepertoryId = "94fa00b6-628c-4a42-a4ca-5e3398dbdbc0",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "7ba3ea10-d840-476d-9de2-d519e8dd927d",
                            RepertoryId = "40e5a01f-34d0-446f-a954-6057150ec540",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "79ccf17c-cf2a-4333-955a-4e3d0e1e7779",
                            RepertoryId = "334fb052-927e-43ae-b032-e18de7dd81ce",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "6cace3e7-6c83-43c6-9f43-292f27b6df1b",
                            RepertoryId = "f1a264a5-045c-4107-9ef6-8ca65d7df47c",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "ba920d87-0742-4744-8016-738e9b0ed806",
                            RepertoryId = "a658c6b0-20fd-43b7-a603-52bee735a01a",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "8cc77fc6-a0c0-45b6-a8a3-796082524195",
                            RepertoryId = "37b06319-09db-4b97-8f78-98f51f1d8e32",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "0f4f410e-2ca9-490a-aabe-e74570bd6215",
                            RepertoryId = "db2ea23f-e7ce-423e-9bc2-257b2c061d04",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "fdf689f9-9a62-4ff3-8f5d-0a96c3eec95f",
                            RepertoryId = "b9df548d-dde8-4c9d-9124-420e43072641",
                            SeatColumn = 0,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "879bec59-456c-4521-8d2e-fe1c719bdce6",
                            RepertoryId = "5bc15682-2eaa-4baf-86ea-e03db1efe9f1",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "b580890d-a863-4c93-a76d-a8ecd5bc8c00",
                            RepertoryId = "2727ab7e-65a3-437a-a403-c121c87a32bf",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "b26e27ac-0756-4bc9-b8d1-b6a43d3a1c9c",
                            RepertoryId = "e67e8d98-37a8-4310-b51c-d2b2f4c5210f",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "0a9a90bd-7538-46ec-82f0-ff069cb63ad3",
                            RepertoryId = "f0a03776-87cf-47b5-9a6c-679d0906d87e",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "ad46247a-97d3-46e4-8671-3013d97fc193",
                            RepertoryId = "b7b94c44-7346-4448-9030-5883e77047c6",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "f4bc3f65-b1a1-4009-a18c-8041aefc2ee8",
                            RepertoryId = "8e25c8bb-a4a4-4df7-ab04-e8e2f6452a26",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "eb471a69-36b5-4c91-8c7a-bbf0f2a75f21",
                            RepertoryId = "ad3fe353-dca7-4fcd-bc8c-9badbaf1e811",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "64e3b666-a9ae-422b-9ce6-a31dcd8661a8",
                            RepertoryId = "2a1fccf7-7603-4ba5-b4be-044ed500ea75",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "e99a49b9-4824-4225-8331-28a92853bf5a",
                            RepertoryId = "a82ed5c0-e84a-481a-9c6d-78263c07e6ca",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "ac1d856d-a822-4a16-9e21-05b6ab25de7b",
                            RepertoryId = "34e641ec-9bea-4383-8e8b-f949aa764e21",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "d7f98b4a-2b99-4311-9922-db3214c0f1f3",
                            RepertoryId = "750b85d6-9ea1-4b66-942c-4e09f432530b",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "86c5feaa-d54f-4f08-828c-420b54e43fd5",
                            RepertoryId = "00b4ebea-8f60-43c9-b1ff-091053e4f744",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "847d8c4a-30db-4baf-a677-24cc0de9aca4",
                            RepertoryId = "14705128-16f3-4e28-8f2b-63465d15a49c",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "338601bf-d5ed-49c6-b23f-d93a69fc5495",
                            RepertoryId = "e0d1c58d-1db0-4705-b3cb-94e6c861737c",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "29f91823-6aaa-490b-9158-bb60eaa516a9",
                            RepertoryId = "b728d7fe-fa8f-4b97-be85-72a3c2990648",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "8ab7eb12-07f0-46d2-9b27-d1725c4f4807",
                            RepertoryId = "8040c6f9-f275-4752-9363-6d12069cd828",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "e8ba5858-4386-4615-a2e3-30119e658b54",
                            RepertoryId = "ef8b3693-e048-4782-9c25-22456b5230b7",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "3ec21cd4-b1c9-46df-9ac3-b2f0f2cca4b4",
                            RepertoryId = "b8429be8-5561-434d-91a8-731a94dbd95f",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "2caf035e-0e9b-4c6d-b765-1cadefe2af96",
                            RepertoryId = "0b1177fe-0733-42e8-a8c5-35ad8039a14e",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "66a7fa9f-a9a1-4afb-b8e7-b09acc783705",
                            RepertoryId = "f563fb50-26da-4a57-9bcd-b3836614835a",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "0e21a96f-a73b-4ee4-93b5-bc8ca5ff627d",
                            RepertoryId = "8411a5b7-699f-45d4-ab67-ee3a17338424",
                            SeatColumn = 0,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "2b8cba22-e4d8-438e-a0f7-8f1692ec417e",
                            RepertoryId = "18f8b880-1231-4028-9eb6-998e94b62b9b",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "caa44a6d-bfc9-4189-bc44-9159ec63ec78",
                            RepertoryId = "73e61eb8-e1ef-400f-a6b8-b2e07725dfb2",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "7a2546d1-86df-45c1-914f-ff690d5e1298",
                            RepertoryId = "524ce530-f997-44da-b118-2c88be728248",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "71f80387-9133-45a4-82d0-7dce7a5884a1",
                            RepertoryId = "1367d782-f24e-4985-978d-825515f40bee",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "c4e23ecd-04ec-4aee-abde-898863880aed",
                            RepertoryId = "5417a7e6-e108-48ff-b831-6578c3680a71",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "de8fa025-3b07-4e9b-ab6f-ba97d5e130ab",
                            RepertoryId = "c80f93cc-c780-436d-800a-f3ba02aabcdc",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "1fa785bd-6ff6-42b3-8014-a27aa42cfc30",
                            RepertoryId = "ef0f138d-b306-4983-a873-1222342b4368",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "0029c322-590d-40d0-8a6e-a42dc01845ea",
                            RepertoryId = "87950de7-b4a3-430b-add8-57cb2f696aa6",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "c67d78c9-b9e2-4b7d-8cb9-f4f7deaf7bbe",
                            RepertoryId = "86d5fad3-0481-4497-9dab-b97a7da4c13c",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "f2c45740-6bc5-4caf-ac79-4ca7fa88310b",
                            RepertoryId = "2ce9ef7b-77f0-49e8-8277-fe90927f3ce7",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "0c39f474-2e5e-4b4c-bcd4-f49d8b94247d",
                            RepertoryId = "8ad3aba2-5caa-40ca-afdb-d62f9253ed01",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "30fcbd9d-c52c-40c3-bc6f-949bd1579ae7",
                            RepertoryId = "4f8eb2ca-3a70-4920-8de0-5033ed304451",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "53b6b554-ab87-46b4-b7f3-12e2cdc871a4",
                            RepertoryId = "1dd5a479-a903-426e-9880-4eeef60b69f8",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "aa97e907-1acd-437c-8234-3e737c62cc6b",
                            RepertoryId = "f6f1670a-4eba-4d98-85f6-d4c1d37a7dec",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "a8f193e4-8cd2-4fc9-b398-c91252e64c80",
                            RepertoryId = "f6a55375-3743-4528-8ac4-8ba93e9ba017",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "ae88c00f-5480-430e-b77b-aa6c66544747",
                            RepertoryId = "17738e0f-d311-4003-b6c2-7a8bfe733e20",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "3ea6c925-4e7f-4c67-9b33-879b6f2afec4",
                            RepertoryId = "067273f1-2931-4cf5-9f0f-0893fa7ec83e",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "8952b240-86e8-443b-a8be-75b3c448b0b9",
                            RepertoryId = "2339db48-b2bc-481d-9d78-ebb9e32f433d",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "9f3ba46d-a993-4780-8d40-91bcbe8a9269",
                            RepertoryId = "661ac04f-8289-4eec-9530-c648264eb9a4",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "663f74c2-e109-480d-9a27-4d6d17e34e91",
                            RepertoryId = "f7c4ec9d-e923-4d28-8918-ac842efc24e5",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "8c3d59e5-51bd-4413-8a98-a3bb10b6b46d",
                            RepertoryId = "fa858d18-c031-4a4d-8700-7b46f21109f4",
                            SeatColumn = 0,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "a9d7ff1e-f021-482e-be3e-7a7bcbf62c93",
                            RepertoryId = "1bbd4048-bbf7-4269-a4a1-bf0510fd18db",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "04454f21-bfef-47f4-a161-2835c637f6d0",
                            RepertoryId = "149d67fb-796f-489b-bbe2-993073b66bc6",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "391ffd06-7034-46df-a9b0-ddfaf9baa269",
                            RepertoryId = "23fc35c2-cd81-45be-bf32-b2cb1da3bc34",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "9f031906-139a-4a0a-90a1-f81998dc1bab",
                            RepertoryId = "2128363b-df77-4459-85aa-2beaf899ec4c",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "aa234243-8ef5-40ad-ad43-71b5f11a1ba5",
                            RepertoryId = "a9c0be59-ab64-4b33-8f03-26bd93aab48e",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "ab9a247f-eb69-480f-8350-44a206d8a99d",
                            RepertoryId = "a7dd1624-9980-48f4-b73a-56660e673c89",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "8dd28a3f-9b98-40b2-a5e4-d636c775dd21",
                            RepertoryId = "c6163527-6edf-43e2-a07b-f4889a37f70e",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "87efe45f-a36d-4c68-bd45-93a7110e4854",
                            RepertoryId = "f56de32e-a8d4-495b-99dc-a3867d7408f0",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "98f1adb1-4922-49f0-9273-17e16c8c456b",
                            RepertoryId = "7ed80a87-eb47-4249-8ac1-917a0800496c",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "2925a44b-31bf-456b-ba90-49451e2f88c0",
                            RepertoryId = "eacf5f01-e97f-412e-9ae0-a627b999bdeb",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "124260b2-0524-41b1-9404-6007dfa27721",
                            RepertoryId = "9fff2c90-0b6f-4974-864c-8f54a86edb4b",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "3f4f1950-fabf-412e-85f0-7240ecbea2f7",
                            RepertoryId = "a840daac-d9a9-4c16-a48a-043e43247034",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "372c4b21-599c-4d7e-8f18-95e0d7d96d87",
                            RepertoryId = "e4ed83ca-81a4-4ea0-a7ef-5e4062faa9fa",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "07bd83fc-3c71-4a79-bd08-fcbeb1e9eecf",
                            RepertoryId = "29fe55f5-1a1f-40ad-8db4-9b6731040db2",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "78297f80-68e3-45d5-9594-fbae881c597d",
                            RepertoryId = "c6a09e5f-f947-4c64-9b18-16aac2afe1b7",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "a45147f9-5344-4db7-83b4-c2e911546612",
                            RepertoryId = "7fe64e0c-3586-4164-a6b5-e336b032bd4a",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "710e20ba-3b55-427d-b475-a4b6e443be9a",
                            RepertoryId = "ad23b7ab-3357-4f0d-a134-25d7ed235ef6",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "1053eac7-0932-48f9-a5ad-8da441f927f6",
                            RepertoryId = "a1a5cd9b-768c-44c3-9da7-c159e933da5b",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "ccdb5121-081f-4cab-99dc-4d6b73534c48",
                            RepertoryId = "7b0d2ec2-e0ad-4efc-ba04-8d9453fd6353",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "2fa6df94-a738-4ad9-9bdb-d0b76f96b653",
                            RepertoryId = "f974f0ce-ad88-4ca0-8e1e-a0f235ebe2fd",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "84da0645-079f-43b4-8c28-18d50e8e4dad",
                            RepertoryId = "4b0c1825-74c9-4b7c-be7e-42a25038e481",
                            SeatColumn = 0,
                            SeatRow = 3,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "0e1635d2-d5e7-48e1-ae16-07e1f8bfabed",
                            RepertoryId = "a36ce8fb-2240-4440-8fb9-2e09c1a21dba",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "883f7ad2-49d0-4514-9ec1-b15726f7b366",
                            RepertoryId = "d859c610-740e-4955-878b-06fe614a1998",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "e1839a50-1534-467c-a80f-062b4df8e38b",
                            RepertoryId = "4282c7e6-4904-4a11-83a4-bf5278775272",
                            SeatColumn = 1,
                            SeatRow = 0,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "56398c59-d78b-48d7-a5eb-59e391484173",
                            RepertoryId = "646458e6-6060-4dcc-9118-b14ce4c1fe28",
                            SeatColumn = 1,
                            SeatRow = 2,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "511187ce-c6ab-4f45-9f39-26407176fa64",
                            RepertoryId = "a1c414ac-30c6-44fa-84fe-8ed9bba25611",
                            SeatColumn = 3,
                            SeatRow = 0,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "785aaa33-3cec-4579-9a0b-8dc111cdfe71",
                            RepertoryId = "8cf9c962-93ad-429c-9347-6fb6022a1f37",
                            SeatColumn = 2,
                            SeatRow = 1,
                            UserId = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9"
                        },
                        new
                        {
                            Id = "2d3f567c-e412-4468-8287-0f8d8a59b3d1",
                            RepertoryId = "0002ce82-5bf2-4b33-9d69-6c4c3f09f36a",
                            SeatColumn = 2,
                            SeatRow = 3,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "46acd887-1af8-4e5f-b07e-f799ca17ebdb",
                            RepertoryId = "43161eb5-a4a4-455f-b402-fb7d7c73b98a",
                            SeatColumn = 0,
                            SeatRow = 1,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        },
                        new
                        {
                            Id = "72d56867-33f0-4172-84c2-ef83776d95fc",
                            RepertoryId = "921112c1-f48f-4d06-9ae8-81b8c663fa2a",
                            SeatColumn = 3,
                            SeatRow = 2,
                            UserId = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
