// <auto-generated />
using Cinema.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinema.WebApi.Migrations.User
{
    [DbContext(typeof(UserContext))]
    [Migration("20200402201554_updateUser")]
    partial class updateUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinema.WebApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Birthday")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e",
                            Birthday = "4/1/1994",
                            Email = "user@cinemate.com",
                            Name = "Petar",
                            Password = "Y2luZW1hdXNlcg==",
                            Role = "User",
                            Surname = "Petrovic",
                            Username = "user"
                        },
                        new
                        {
                            Id = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9",
                            Birthday = "11/5/1993",
                            Email = "user2@cinemate.com",
                            Name = "Mile",
                            Password = "Y2luZW1hdXNlcjI=",
                            Role = "User",
                            Surname = "Mikic",
                            Username = "user2"
                        },
                        new
                        {
                            Id = "a7cb6058-be25-4d4f-8649-0839839a879c",
                            Birthday = "4/6/1990",
                            Email = "user3@cinemate.com",
                            Name = "Aleksa",
                            Password = "Y2luZW1hdXNlcjM=",
                            Role = "User",
                            Surname = "Gavric",
                            Username = "user3"
                        },
                        new
                        {
                            Id = "03491b89-9e02-422e-a082-9c63c5f10c02",
                            Birthday = "9/8/1994",
                            Email = "admin@cinemate.com",
                            Name = "Jovan",
                            Password = "Y2luZW1hYWRtaW4=",
                            Role = "Administrator",
                            Surname = "Lukic",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
