// <auto-generated />
using Cinema.WebApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinema.WebApi.Migrations.User
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinema.WebApi.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "2ea08fcd-3b57-43a5-8bcc-37fa8c99533e",
                            Email = "user@cinemate.com",
                            Name = "Petar",
                            Password = "Y2luZW1hdXNlcg==",
                            Role = "User",
                            Surname = "Petrovic",
                            Username = "user"
                        },
                        new
                        {
                            Id = "fcce9446-45f6-40f9-a8de-8d8ba40aebf9",
                            Email = "user2@cinemate.com",
                            Name = "Mile",
                            Password = "Y2luZW1hdXNlcjI=",
                            Role = "User",
                            Surname = "Mikic",
                            Username = "user2"
                        },
                        new
                        {
                            Id = "a7cb6058-be25-4d4f-8649-0839839a879c",
                            Email = "user3@cinemate.com",
                            Name = "Aleksa",
                            Password = "Y2luZW1hdXNlcjM=",
                            Role = "User",
                            Surname = "Gavric",
                            Username = "user3"
                        },
                        new
                        {
                            Id = "03491b89-9e02-422e-a082-9c63c5f10c02",
                            Email = "admin@cinemate.com",
                            Name = "Jovan",
                            Password = "Y2luZW1hYWRtaW4=",
                            Role = "Administrator",
                            Surname = "Lukic",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
