// <auto-generated />
using Cinema.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinema.WebApi.Migrations.Hall
{
    [DbContext(typeof(HallContext))]
    [Migration("20200330214623_HallsUpdaet")]
    partial class HallsUpdaet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinema.WebApi.Models.Hall", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cloumns")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Cloumns = 5,
                            Name = "A1",
                            Rows = 5
                        },
                        new
                        {
                            Id = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Cloumns = 5,
                            Name = "A2",
                            Rows = 5
                        },
                        new
                        {
                            Id = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Cloumns = 5,
                            Name = "B1",
                            Rows = 5
                        },
                        new
                        {
                            Id = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Cloumns = 5,
                            Name = "B2",
                            Rows = 5
                        },
                        new
                        {
                            Id = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Cloumns = 5,
                            Name = "C",
                            Rows = 5
                        });
                });

            modelBuilder.Entity("Cinema.WebApi.Models.Seat", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cloumns")
                        .HasColumnType("int");

                    b.Property<string>("HallId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Reserved")
                        .HasColumnType("bit");

                    b.Property<int>("Rows")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = "56e5c918-ad2a-4155-b603-7845dd38ba1e",
                            Cloumns = 0,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "d083f5f0-ef8d-4b1a-80dd-40accc1c35cc",
                            Cloumns = 1,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "04f190a1-2c34-422b-a2cc-caab920b3dfc",
                            Cloumns = 2,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "2e9d0512-4e01-45ce-a33b-de756782c4aa",
                            Cloumns = 3,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "0439fd36-51e8-40be-93b8-3922f8367021",
                            Cloumns = 4,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "7dcd0666-2fd8-48f2-b4a0-b5e924309d19",
                            Cloumns = 0,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "9c5c6814-b91b-44a6-9b3b-36daf4cafa80",
                            Cloumns = 1,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "5f3a955a-58d6-410b-8948-4caad00a6c38",
                            Cloumns = 2,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "a1439397-2c27-464b-b4d8-de0d9f08c949",
                            Cloumns = 3,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "44bdafbd-ec60-48a5-b09f-2c88fc8883d4",
                            Cloumns = 4,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "1c762d65-31fd-4322-9576-13db6994add9",
                            Cloumns = 0,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "b125792c-f6f7-48d6-9091-d6bdf420e91f",
                            Cloumns = 1,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "05346977-1f66-4d5d-8322-47bef0db2798",
                            Cloumns = 2,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "99a82bb2-fcb4-4c26-9192-a2b730c951df",
                            Cloumns = 3,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "c4121250-5c2c-4afc-831c-7ea4d5df1df4",
                            Cloumns = 4,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "2440a7d6-52a8-479f-83d1-46bda96abf0c",
                            Cloumns = 0,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "9eb5ed9e-e34e-4994-ad36-2ce8242946e8",
                            Cloumns = 1,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "93933b08-5fb9-4af3-a7d4-dd5b0ec15b6d",
                            Cloumns = 2,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "6de3a229-6853-4f09-adf6-90ed826681d2",
                            Cloumns = 3,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "87a5fab2-b0a5-45aa-8866-3658b1da2601",
                            Cloumns = 4,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "9ccce127-9bb0-4161-8eee-7040dfefa4c6",
                            Cloumns = 0,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "d326cfb9-7caa-40ac-be9f-31ab54a25cd4",
                            Cloumns = 1,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "74f36294-6703-426b-8900-bc037b4eeb18",
                            Cloumns = 2,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "0ccf7502-6c59-4cc8-aa39-cf94f7e3158f",
                            Cloumns = 3,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "1c48da3c-7378-475e-a4bc-21bdd0ada10f",
                            Cloumns = 4,
                            HallId = "b43eba05-74e4-45ea-bf32-0ca5b8f85003",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "5bc04d32-a3e9-4e48-bb72-6acd121a8fcb",
                            Cloumns = 0,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "bee03286-d2dd-425f-94cf-90b5d87ff39f",
                            Cloumns = 1,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "5fe7fd89-3ac3-457d-9b4b-000e81d38cf8",
                            Cloumns = 2,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "a312cc37-bafb-48e8-9d66-914d208d944d",
                            Cloumns = 3,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "87f0eb29-9f41-4286-a5ef-298395df364e",
                            Cloumns = 4,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "3fdb838a-29f6-4cad-9cf0-46677026a003",
                            Cloumns = 0,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "879a215b-c50a-474a-a8f3-e5ca16a6b63e",
                            Cloumns = 1,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "1358ea9b-f8fa-45ff-b40b-1a8bb5d5760f",
                            Cloumns = 2,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "4f9ca8d4-b37e-4edf-b038-367a88fd21ed",
                            Cloumns = 3,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "e682fa7b-1722-4edf-9a23-aaf6ba1f1783",
                            Cloumns = 4,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "1f07be32-760f-4675-a125-f7c80f6ccc67",
                            Cloumns = 0,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "b8699479-0b32-47ac-9f63-3a2407b41229",
                            Cloumns = 1,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "1ee48e39-a246-4bfb-bb4c-6fe97ad52c6e",
                            Cloumns = 2,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "b9734e1b-6acc-4b90-83c7-828bd5b31a08",
                            Cloumns = 3,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "5cd9f708-51e7-4894-8835-132afe28b5c6",
                            Cloumns = 4,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "9e992f87-91f0-41f0-adc3-88cd363fdc82",
                            Cloumns = 0,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "a4b9824a-13f7-43e9-b077-a9737dd1c5ed",
                            Cloumns = 1,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "7968df5c-5b70-4491-b063-18b8264fc0c2",
                            Cloumns = 2,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "876ef10d-bf60-4927-8f9d-a679c7cf8242",
                            Cloumns = 3,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "6b839810-fe37-447d-b7d5-dac9c492083c",
                            Cloumns = 4,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "fdcc86f6-4f55-43df-aee4-8423bed6a48e",
                            Cloumns = 0,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "62d6164b-0a51-488f-b93f-a78a262f7e6b",
                            Cloumns = 1,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "ada6c4b9-b64a-46f6-a1be-59d4f19c22d8",
                            Cloumns = 2,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "1bd87a68-944d-44f6-ad96-df197af5d213",
                            Cloumns = 3,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "46832092-f47e-4690-b8c6-2a0eb0810788",
                            Cloumns = 4,
                            HallId = "d0cdd288-de39-4a5d-9c7b-aac041e49414",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "38e38174-a702-4c3b-b21c-f12b9d97e957",
                            Cloumns = 0,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "727724bc-c041-4c14-b5ca-328c086bea46",
                            Cloumns = 1,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "6e6cfbff-7aa6-4cab-abed-d0341d3b10ed",
                            Cloumns = 2,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "106f79e3-b3b7-48f0-8311-3657813a81de",
                            Cloumns = 3,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "41f3e0b6-aa0d-4dba-a89b-13bbfc8cbe9a",
                            Cloumns = 4,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "27edd058-4fdb-49fe-bc7d-7d36831b26f7",
                            Cloumns = 0,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "eab2321a-33de-4e4f-a10e-48567d819546",
                            Cloumns = 1,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "dc29a733-10b4-4adc-8324-4c2481b08f18",
                            Cloumns = 2,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "76e61be1-b749-4c94-980a-825cd526ba5f",
                            Cloumns = 3,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "7a9981b3-d4a3-46a8-b095-cd354d4f07fd",
                            Cloumns = 4,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "e7f4b23a-090d-4d24-b58d-7d90e884dff2",
                            Cloumns = 0,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "4255dd46-aab2-45c2-a53b-05f904e9ed49",
                            Cloumns = 1,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "50f900c3-ce12-450d-977e-e5639147b915",
                            Cloumns = 2,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "3c8a9d0f-2d0f-4d5d-bf64-a9785f9862b3",
                            Cloumns = 3,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "16984c1a-3f21-4314-a50e-954a34201caa",
                            Cloumns = 4,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "6cf368bc-53aa-4eb0-b93c-e6a9263646b7",
                            Cloumns = 0,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "923037d6-301b-4508-bba2-027d2acd850a",
                            Cloumns = 1,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "29c82e9e-31f2-41fd-9d81-cecc885e9324",
                            Cloumns = 2,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "9fe3099a-7d29-4af8-a87c-6e1449081c8f",
                            Cloumns = 3,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "ca7e0f41-65fd-4b9f-8eea-3a315997503b",
                            Cloumns = 4,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "8bb30dcf-83dc-494c-a800-04c0142fa1d2",
                            Cloumns = 0,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "d730053f-a822-4c0e-804f-c7c8cfa8295f",
                            Cloumns = 1,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "f2cfce18-6f51-43be-b54e-86e91d328b79",
                            Cloumns = 2,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "5d6ac0ea-e4a1-4d4c-816e-e80dbd9fe1f2",
                            Cloumns = 3,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "c68f34cc-f174-4d16-ae3f-08bfc894de5d",
                            Cloumns = 4,
                            HallId = "5019e093-32fa-42a0-bf18-dfd3724cc853",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "81d03def-1bc6-4839-8eb5-6b5076ce9e84",
                            Cloumns = 0,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "85c7a956-40e6-46b2-b3a5-f61831b38c7e",
                            Cloumns = 1,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "4bd412f8-19a0-4758-9b32-8091f9a14aae",
                            Cloumns = 2,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "a510d57a-6777-44b9-8fb4-c61ff0eaff55",
                            Cloumns = 3,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "659b26bb-d392-4514-a437-b1f748c70693",
                            Cloumns = 4,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "2169dd9b-2cf7-4ac9-9152-95859c5c1c64",
                            Cloumns = 0,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "75a14b59-070d-4f2b-af07-e7b95e9c89fd",
                            Cloumns = 1,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "106479cd-55d4-4c47-9fd1-efe2575eee90",
                            Cloumns = 2,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "d3f602fb-227c-4b01-81be-a01ae8939674",
                            Cloumns = 3,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "63cc555d-d86a-41c1-ac3a-2d3c83c1612c",
                            Cloumns = 4,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "16eabf86-fb6a-4f07-a65f-15ca3cd60d17",
                            Cloumns = 0,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "856947ac-741a-4ba3-be59-8b1b7b0f40f4",
                            Cloumns = 1,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "3f7d42e8-c7dd-4ed5-b181-e3db8e934e9a",
                            Cloumns = 2,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "10628390-21a3-4a99-b864-b8bf7ce254c1",
                            Cloumns = 3,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "9f121815-0cbc-4bd8-a62d-01969dfd1513",
                            Cloumns = 4,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "82083d31-7620-4e22-ae6d-e8283355c452",
                            Cloumns = 0,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "7f8bd4dc-d5c6-4413-bbe1-384b382535de",
                            Cloumns = 1,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "1872d67d-1126-4892-9950-7b68a351a9e3",
                            Cloumns = 2,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "cc136fb7-b60b-469c-bf68-5ba23b5df28d",
                            Cloumns = 3,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "4068f440-f302-4d22-8716-48bff5008225",
                            Cloumns = 4,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "bf413682-c35c-4acb-a275-950281a09b9e",
                            Cloumns = 0,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "d2342648-9cfa-4fc9-9e04-ae6d485631f7",
                            Cloumns = 1,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "1a0f2584-a267-4d25-b3e6-6d07cb78122c",
                            Cloumns = 2,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "c1bc385f-6cee-459d-b0d6-a97b5c139d0c",
                            Cloumns = 3,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "c67f9aa9-4c94-4b1c-b0ce-6cd8aed0ac53",
                            Cloumns = 4,
                            HallId = "ed5e3547-bf44-437c-8f9f-a94036ae860c",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "edb0e8b6-c0cc-4577-9791-c82ca8c400c8",
                            Cloumns = 0,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "70f9ead6-7291-41e2-88ea-ef72b66644f1",
                            Cloumns = 1,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "46e3ba43-2c11-4a3e-a3f3-af1476a0c87a",
                            Cloumns = 2,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "037a54dc-79bb-4d9b-bd75-835e22ea8857",
                            Cloumns = 3,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "8776699a-cbf5-4e65-ab1a-8514b8b92b10",
                            Cloumns = 4,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 0
                        },
                        new
                        {
                            Id = "82e07ee3-b67d-43d1-b8f7-bf574e9d32fe",
                            Cloumns = 0,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "79841fdb-4310-491f-a0d9-73e268281eb2",
                            Cloumns = 1,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "37969092-29e2-4614-ba1d-a8b5180acd45",
                            Cloumns = 2,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "16dd8ef2-de2c-4b89-b72e-171912968508",
                            Cloumns = 3,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "d732986f-a4fc-497b-8e92-a63dc8df3401",
                            Cloumns = 4,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 1
                        },
                        new
                        {
                            Id = "64a6fd8b-c695-4d49-a5a5-9ca5f3a2fa04",
                            Cloumns = 0,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "600c5a3b-9744-453c-8da4-bc66301f7a52",
                            Cloumns = 1,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "86cc9364-f99d-480e-9fca-a686f5c5c545",
                            Cloumns = 2,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "2cdb9577-6bbc-42bb-8225-de11dd2e13d5",
                            Cloumns = 3,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "f264d63d-9fc3-4889-8e89-181dd2a413d9",
                            Cloumns = 4,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 2
                        },
                        new
                        {
                            Id = "3290a60a-eef6-4145-8818-ed87c935f15f",
                            Cloumns = 0,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "fb334632-736f-4bdc-8a56-94059bf4b9dd",
                            Cloumns = 1,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "a6fb2180-aefe-4af3-a9b2-52060c1a03fc",
                            Cloumns = 2,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "390e0e9f-c5f5-421b-9e50-5d9959bd0b5f",
                            Cloumns = 3,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "e0ce2d29-4912-4933-a3ec-9c20daca88ab",
                            Cloumns = 4,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 3
                        },
                        new
                        {
                            Id = "c0073873-6ebf-406f-ad5b-bac80e49e1e1",
                            Cloumns = 0,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "6e884d7d-f935-4cec-930d-a818e770a0a0",
                            Cloumns = 1,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "084569d4-da57-47a3-8e55-9239123d3b1b",
                            Cloumns = 2,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "01a0599b-6277-4c14-a4d2-58e83741746e",
                            Cloumns = 3,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 4
                        },
                        new
                        {
                            Id = "3c349739-f56c-4df7-8db1-7751780a8354",
                            Cloumns = 4,
                            HallId = "01a2f471-b69d-4e68-9924-96e32351ab8d",
                            Reserved = false,
                            Rows = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
