// <auto-generated />
using Cinema.WebApi.Contexts;
using Cinema.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Cinema.WebApi.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20191103152643_Cinema.WebApi.Models.MovieContextSeed")]
    partial class CinemaWebApiModelsMovieContextSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Cinema.WebApi.Models.Movie", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Actors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poster")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Released")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Runtime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Writer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = "9b227d7b-c427-4dc5-9f82-77c307f69ac0",
                            Actors = "Hrithik Roshan, Tiger Shroff, Vaani Kapoor, Ashutosh Rana",
                            Country = "India",
                            Genre = "Action, Thriller",
                            Plot = "An Indian soldier is assigned a mission to eliminate his former mentor, who has gone rogue.",
                            Poster = "https://m.media-amazon.com/images/M/MV5BNTlmNDMzOWQtYzg4Ny00OWQ0LWFhN2MtNmQ2MDczZGZhNTU5XkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg",
                            Rated = "Not Rated",
                            Released = "02 Oct 2019",
                            Runtime = "154 min",
                            Title = "War",
                            Writer = "Siddharth Anand (screenplay), Siddharth Anand (story), Aditya Chopra (story), Shridhar Raghavan (screenplay), Abbas Tyrewala (dialogue)",
                            Year = "2019"
                        },
                        new
                        {
                            Id = "ee2fddbe-ac9b-4e9a-84e4-0c390fa7c3e9",
                            Actors = "Alban Lenoir, Olga Kurylenko, Sébastien Lalanne, David Murgia",
                            Country = "France, Belgium",
                            Genre = "Action, Drama, History, War",
                            Plot = "In February 1976 in Djibouti, a school bus was taken hostage at the Somali border. The GIGN is sent on the spot. After 30 hours of tension, a rescue operation is organized.",
                            Poster = "https://m.media-amazon.com/images/M/MV5BMDZiNDcxYzItN2JhNy00MjgxLTgyNjMtNzdiOWU1Y2MwODYxXkEyXkFqcGdeQXVyNzc0MTgzMzU@._V1_SX300.jpg",
                            Rated = "TV-14",
                            Released = "30 Jan 2019",
                            Runtime = "98 min",
                            Title = "15 Minutes of War",
                            Writer = "Ileana Epsztajn (collaboration), Fred Grivois (screenplay), Jérémie Guez (collaboration)",
                            Year = "2019"
                        },
                        new
                        {
                            Id = "c75c376c-5fa3-4eff-9b4d-f8281f3a81e7",
                            Actors = "Darcie Lincoln, Peter Cosgrove, Victor Toth, Georgia Wood",
                            Country = "UK",
                            Genre = "History",
                            Plot = "Ingrid and her siblings are on the run from the Beserkers who have begun invading the villages, taking over, savagely using the residents on a game where they vs a Beserker, and if they win...",
                            Poster = "https://m.media-amazon.com/images/M/MV5BYTAwNjg3ZDUtZWYxOS00MGVjLTkyYTYtYjJhOGRhNmQzODRkXkEyXkFqcGdeQXVyMjM4MTU4NjQ@._V1_SX300.jpg",
                            Rated = "N/A",
                            Released = "05 Feb 2019",
                            Runtime = "103 min",
                            Title = "The Viking War",
                            Writer = "Suzy Spade",
                            Year = "2019"
                        },
                        new
                        {
                            Id = "36100801-5f5b-4795-806e-a5df0b434493",
                            Actors = "Karra Elejalde, Eduard Fernández, Santi Prego, Luis Bermejo",
                            Country = "Spain, Argentina",
                            Genre = "Drama, History, War",
                            Plot = "July 18, 1936. Salamanca, Castilla and León (center to Spain). The Spanish army declares in the city the state of war, hoping to extend it to the rest of Spain and improve the unstable ...",
                            Poster = "https://m.media-amazon.com/images/M/MV5BOGZjZDgxYTItMDQwYS00MWQ1LTk3ZGEtNjY1MmIwNDk5OWZjXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg",
                            Rated = "N/A",
                            Released = "27 Sep 2019",
                            Runtime = "107 min",
                            Title = "While at War",
                            Writer = "Alejandro Amenábar, Alejandro Hernández",
                            Year = "2019"
                        },
                        new
                        {
                            Id = "d6575425-bb05-417c-9c90-a42baffb2a31",
                            Actors = "Michael Roark, Trace Adkins, Ali Afshar, Allison Paige",
                            Country = "USA",
                            Genre = "Sport",
                            Plot = "After surviving an IED explosion in combat overseas, a young soldier with the Army Motorcycle Unit is medically discharged with a broken back and leg. Against all odds he trains to make an ...",
                            Poster = "https://m.media-amazon.com/images/M/MV5BNzM0Zjc2OWMtY2NjNS00ZmE4LWEzZTItMWE3NjQ4NmM2YzE2XkEyXkFqcGdeQXVyOTk0Mjc1MDA@._V1_SX300.jpg",
                            Rated = "PG-13",
                            Released = "30 Aug 2019",
                            Runtime = "94 min",
                            Title = "Bennett's War",
                            Writer = "Alex Ranarivelo",
                            Year = "2019"
                        },
                        new
                        {
                            Id = "1e699e33-eaca-449d-b5b0-7174f50ec5d6",
                            Actors = "Robert De Niro, Uma Thurman, Christopher Walken, Jane Seymour",
                            Country = "USA",
                            Genre = "Comedy, Family",
                            Plot = "Upset that he has to share the room he loves with his grandfather, Peter decides to declare war in an attempt to get it back.",
                            Poster = "https://m.media-amazon.com/images/M/MV5BZjU0MDRmMjAtZGU2Ny00ODkxLThiMDUtMmI1MDJhNDc5YTZkXkEyXkFqcGdeQXVyMzgxOTMzOTA@._V1_SX300.jpg",
                            Rated = "PG",
                            Released = "27 Dec 2018",
                            Runtime = "141 min",
                            Title = "The War with Grandpa",
                            Writer = "Tom J. Astle (screenplay by), Matt Ember (screenplay by), Robert Kimmel Smith (based on the book by)",
                            Year = "2019"
                        },
                        new
                        {
                            Id = "086729d4-a5a5-46ad-ae7f-7439e6f724cb",
                            Actors = "Sven Schelker, Charlotte Heinimann, Daniel Ludwig, Matthew Crowley",
                            Country = "Switzerland, Austria",
                            Genre = "Drama",
                            Plot = "1984: Searching for an experience that goes deeper than the superficiality of modern civilization, Bruno Manser travels into the jungles of Borneo and finds it with the nomadic Penan tribe....",
                            Poster = "https://m.media-amazon.com/images/M/MV5BZWM1NzEyNDAtZDFhNi00NzBhLTg3MWEtN2Y1YjI5YTYzZTM5XkEyXkFqcGdeQXVyNDkzNTM2ODg@._V1_SX300.jpg",
                            Rated = "N/A",
                            Released = "26 Sep 2019",
                            Runtime = "142 min",
                            Title = "Paradise War: The Story of Bruno Manser",
                            Writer = "David Clemens, Niklaus Hilber, Patrick Tönz",
                            Year = "2019"
                        },
                        new
                        {
                            Id = "155727bb-39c1-4734-ab48-a05d74756906",
                            Actors = "Christina Milian, Adam Demos, Jeffrey Bowyer-Chapman, Anna Jullienne",
                            Country = "USA",
                            Genre = "Comedy, Romance",
                            Plot = "When city girl Gabriela spontaneously enters a contest and wins a rustic New Zealand inn, she teams up with bighearted contractor Jake Taylor to fix and flip it.",
                            Poster = "https://m.media-amazon.com/images/M/MV5BNWE1NmMzNjUtMDc3NS00ZjBlLTllMTktZTVkMWQzZGVlYzdhXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
                            Rated = "TV-PG",
                            Released = "29 Aug 2019",
                            Runtime = "98 min",
                            Title = "Falling Inn Love",
                            Writer = "Elizabeth Hackett, Hilary Galanoy",
                            Year = "2019"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
